language: objective-c
osx_image: xcode7.3
cache: cocoapods
podfile: Tests/Podfile

rvm: 2.2.2

before_install:
- gem install cocoapods

before_script:
- export LANG=en_US.UTF-8

script:
- xctool -workspace SwiftJSONRPC.xcworkspace -scheme SwiftJSONRPCTests -sdk iphonesimulator test
- pod lib lint
